vim_plugin_task "vimclojure",       "https://github.com/vim-scripts/VimClojure.git"
vim_plugin_task "vim-repeat",       "https://github.com/tpope/vim-repeat.git"

skip_vim_plugin "fugitive"
skip_vim_plugin "git"
skip_vim_plugin "indent_object"
skip_vim_plugin "surround"
skip_vim_plugin "vividchalk"
skip_vim_plugin "zoomwin"
skip_vim_plugin "snipmate"
skip_vim_plugin "align"
skip_vim_plugin "searchfold"
skip_vim_plugin "align"
skip_vim_plugin "puppet"
skip_vim_plugin "scala"
skip_vim_plugin "gist-vim"
skip_vim_plugin "arduino"
skip_vim_plugin "vwilight"

